### ISSUE TITLE
Windows managers and apps categories

### ISSUE THREAD

**Issue by aleksandar-todorovic** [aleksandar-todorovic/awesome-linux#1]
**EDIT**: The categories are now created but there's no content in them for now.

To add new content, please refer to the `CONTRIBUTING.md` file.

As for the `X Windows Managers` subsection, I've sent a request to @dhamaniasad to merge his content. There should also be some rules set in the `CONTRIBUTING.md` file. I can't set them on my own because of my very limited experience in working with windows managers.

**Comment by sindresorhus** [comment]
Inspiration: https://github.com/dhamaniasad/awesome-linux#x-window-managers

**Comment by aleksandar-todorovic** [comment]
Idea: while adding apps to the apps category, they should be organized into two sub-categories: terminal-only and apps with a GUI. When an app with a GUI are added, it could be useful to state with what Desktop Environment should be used for the best integration.

**Comment by aleksandar-todorovic** [comment]
These changes have already been implemented. Closing this.
