### ISSUE TITLE
Add a section dedicated to the special purpose Linux distributions

### ISSUE THREAD

**Issue by MichaelSp** [aleksandar-todorovic/awesome-linux#13]
Maybe adding [CoreOS](https://coreos.com/) to the list is a good idea, as this is getting more traction.

**Comment by aleksandar-todorovic** [comment]
From [`contributing.md`](https://github.com/aleksandar-todorovic/awesome-linux/blob/master/CONTRIBUTING.md#distributions-section)

> **Distributions section**

> There will be no more distributions added to this section. For the sake of keeping this list short, only top 10 distributions from Distrowatch's list for the last 12 months will be included. Also, to avoid personal opinions about them, the Distrowatch descriptions are copied. If you think they're outdated or short, please contact Distrowatch and let me know.

**Comment by MichaelSp** [comment]
Oh sorry, didn't see this. 
But maybe there is a "Headless" section missing?!

**Comment by dhamaniasad** [comment]
Maybe we could have a "Special Purpose"(or some similar) section, for distributions like Puppy, which is built for running on old computers, and CoreOS, which is built for clusters, and so on.

**Comment by aleksandar-todorovic** [comment]
My problem with that section is that it could become very big very quickly. As an example, in that section we could put Kali, Ubuntu Studio etc. Since there's a large number of special purpose distributions and there are multiple distributions designed for a single purpose, we would need to have a certain criteria about which ones are appropriate and which ones are not.

If we decide to do so, my suggestion is to include only a single distribution for a single purpose and that we should decide which one to include by looking at Distrowatch. So, for example, even though Kali and Backbox are both designed for penetration testing, Kali would be included since it's more popular on Distrowatch.

**Comment by dhamaniasad** [comment]
That sounds fair. A single distro per purpose would keep the list from getting too big.

**Comment by MichaelSp** [comment]
I don't know if that has been discussed already, but in comparison to other [awesome-lists](https://github.com/sindresorhus/awesome) this list is pretty small. But Linux is a huge topic. 
On this list there is a quit big description as compared to other lists.
So I'd suggest not to fear a big list, and keep the description shorter (remove screenshots?), in order to be awesome-compliant(tm). After all the projects should describe what they are doing, not this list.
IMHO

**Comment by aleksandar-todorovic** [comment]
@MichaelSp I'm one of the maintainers of that list of awesome lists. I know how thing go. :smiley: 

The whole point of awesome lists is to include awesome materials. Not everything. So, while this list should have a bit more content, we have to be extra careful not to recommend something that is not genuinely awesome.

**Comment by MichaelSp** [comment]
Well my intuition is, if I go to an awesome-list I want to find links to awesome stuff, I don't know about yet. Recently I was looking for an awesome backup solution and I expected to find it in the awesome-linux list (That's why I'm here). I noticed that CoreOS is missing in this list, and I'd consider this to be awesome. 
I understand that this list can't contain everything. And ranging from distros to backup solutions is a huge spread. But to be truly awesome it should also contain what I'm looking for. I think the claim (awesome linux) is a big one, so the list have to be big. But not in description size or number of images, but rather in number of links.

So what is awesomeness? I think it is:
* Find a link to an awesome project/tool/app/website that scratches my itch.

What does that mean for this list?
* The linked project have to be awesome
* This site should have the link

You already have that fully covered given that popularity = awesomeness. But thats not always the case. 

Suggestion:
* shorten the description to one line
* remove the images
* introduce a whole lot more sections. The number if items per section should not be limited by pure numbers, but rather by awesomeness of the project (not to mix it with popularity).

Oh, I've completely lost track. It was about the name of the section for CoreOS right?
How about "Cloud-OS"?

Btw: I just found [awesome-sysadmin](https://github.com/kahun/awesome-sysadmin) where backup solutions are listed already.

**Comment by aleksandar-todorovic** [comment]
> shorten the description to one line

Summing up the whole distribution and its philosophy into a single sentence seems a bit hard. I'm more comfortable using someone else's summary.

> remove the images

Every experienced Linux user is going to assume that he doesn't need to see the distributions section and can just skip it. Pictures can have an impact on someone who wants to try another distribution. I'm willing to reconsider this, but I think that this discussion should be placed in a different (new) issue.

> introduce a whole lot more sections. 

I'm all up for introducing more sections.

> The number if items per section should not be limited by pure numbers, but rather by awesomeness of the project (not to mix it with popularity).

I want the popularity to have an impact _only_ in the distribution section. The reason for that is that I want to avoid fanboyism as much as possible. Popularity will have no impact to any other section what so ever.

**Comment by MichaelSp** [comment]
Well, but CoreOS actually *is* a distribution.

**Comment by aleksandar-todorovic** [comment]
Like I said, special purpose distributions should have their own section. I don't think that there's a more popular distribution that does the same thing as CoreOS, so CoreOS would be included into that section.

**Comment by aleksandar-todorovic** [comment]
Since this was already solved in #14...
