### ISSUE TITLE
Gentoo

### ISSUE THREAD

**Issue by loxdegio** [aleksandar-todorovic/awesome-linux#19]
In Advanced users distros section Gentoo and Slackware are missing, can you add them please?

**Comment by aleksandar-todorovic** [comment]
No.

From [`CONTRIBUTING.md`](https://github.com/aleksandar-todorovic/awesome-linux/blob/master/CONTRIBUTING.md#distributions-section):

> There will be no more distributions added to this section. For the sake of keeping this list short, only top 10 distributions from Distrowatch's list for the last 12 months will be included. Also, to avoid personal opinions about them, the Distrowatch descriptions are copied. If you think they're outdated or short, please contact Distrowatch and let me know.
