### ISSUE TITLE
linux-headers

### ISSUE THREAD

**Issue by Farouk00321** [aleksandar-todorovic/awesome-linux#24]
hi , i have kali linux in virtual box and when i wont to install the linux-header pack . The system can't find 
by the way i had updated my source list

**Comment by aleksandar-todorovic** [comment]
This has nothing to do with this repo. This repo is not a support group. I suggest you to try asking that question somewhere else.

**Comment by Farouk00321** [comment]
sorry  i didn't know i'm new in gitub sorry again

**Comment by dhamaniasad** [comment]
@Farouk00321 I recommend you to try out linuxquestions.org for your query, which is a forum intended for questions like yours. Have a nice day :)

**Comment by Farouk00321** [comment]
thunks
