### ISSUE TITLE
Adding ranger to the list

### ISSUE THREAD

**Issue by Firenox89** [aleksandar-todorovic/awesome-linux#26]
Ranger is console based file manager that IMHO should be added to that list.
https://github.com/ranger/ranger

**Comment by dhamaniasad** [comment]
@firenox89 Looks good to me. Why don't you open a PR for it?

With Regards,
Asad Dhamani

**Comment by Firenox89** [comment]
Done

**Comment by aleksandar-todorovic** [comment]
Solved in #27.
