### ISSUE TITLE
Are kernel resources on-topic here?

### ISSUE THREAD

**Issue by JesseTG** [aleksandar-todorovic/awesome-linux#32]
I'm looking through the documentation for the Linux kernel, and notice that some of these are useful for user-level Linux management, i.e. you can get useful information out of them even if you never do kernel development in your life (some types of configuration, mostly).  Would it be OK if I added said documentation to this list, or is it not within scope?

**Comment by aleksandar-todorovic** [comment]
Could you give me an example?

It probably fits the scope, but just to make sure.

**Comment by JesseTG** [comment]
For example, [this](https://github.com/torvalds/linux/blob/master/Documentation/binfmt_misc.txt) is the official documentation for `binfmt`, the subsystem that lets you run any file as if it were a standalone program (because you associate file extensions or magic numbers with interpreters).  Interesting stuff on its own, but if you look at the link you'll notice that it's all about *using* that subsystem as opposed to *developing* or *modifying* it.

**Comment by aleksandar-todorovic** [comment]
This was definitely an interesting read and I would love to see more material like this in this list!

I propose you create something like `[Advanced] User-level Kernel Management` category below the existing categories and put these parts of the documentation here.

**Comment by JesseTG** [comment]
Sure, I can do that.  I'll keep it to kernel features that most Linux distributions ship with, and I will strictly avoid any that require kernel programming experience to understand or make use of (kernel programming probably deserves its own list).
