### ISSUE TITLE
Blackbox link 404

### ISSUE THREAD

**Issue by hexpunk** [aleksandar-todorovic/awesome-linux#55]
The current link to blackbox window manager, http://blackboxwm.sourceforge.net/, is dead.

I would have just made a PR to change it, but I'm not sure which link is preferred.  Although the Sourceforge site is gone, the project is still there at https://sourceforge.net/projects/blackboxwm/.  However, that page has a link saying the project was moved to https://github.com/bradleythughes/blackbox.  That github project hasn't seen any activity in almost 3 years, though.

**Comment by dhamaniasad** [comment]
The project hasn't seen any activity on Sourceforge in the last 3 years either. Whether it's still fit for inclusion or not aside, if the project says they've moved to the GitHub link, that's the link that we should point to.

**Comment by JayAndCatchFire** [comment]
PR incoming
