### ISSUE TITLE
Distribution description from Distrowatch, not Wikipedia.

### ISSUE THREAD

**Issue by Maphardam** [aleksandar-todorovic/awesome-linux#8]
The Wikipedia articles for the distros are often very short and not useful. Distrowatch provides much better information in a single paragraph.

**Comment by aleksandar-todorovic** [comment]
I had actually thought about it, but decided to go against it once I saw that the description of my preferred Linux distribution (elementary OS) was heavily outdated.

In the meantime, I have contacted Distrowatch and together we updated the description, so now I'm definitely up for it.

**Comment by Maphardam** [comment]
Cool. I'll take care of that.
