### ISSUE TITLE
ScudCloud (opensource Slack client) should be removed from list

### ISSUE THREAD

**Issue by pktiuk** [aleksandar-todorovic/awesome-linux#86]
I have checked ScudCloud from this list and I found out it is inactive since 2018.
It is an archived project without any further support.
https://github.com/raelgc/scudcloud/issues/628
It doesn't have any active fork, so I think it should be removed from the list.

**Comment by dhamaniasad** [comment]
Can you submit a PR for this?

**Comment by pktiuk** [comment]
Added
https://github.com/aleksandar-todorovic/awesome-linux/pull/87
